name: hilo 
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.1
  - pip
  - pip:
    - attrdict==2.0.1
    - loguru==0.6.0
    - numpy==1.23.4
    - pandas==1.5.1
    - PyYAML==6.0
    - scikit-learn==1.1.3
    - spacy==3.4.2
    - tqdm==4.64.1 
    - transformers==4.30.2